config/routes.rb
Rails.application.routes.draw do
    get 'bookings/index'

    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'
    delete  '/logout',  to: 'sessions#destroy'

    get     '/bookings/editstatus/:id/:status',  to: 'bookings#editStatus'

    get     '/rooms/save_room_details/:id/:name/:desc' => 'rooms#save_room_details', :as => 'save_room_details'
    get     '/users/save_user_details/:id/:password' => 'users#save_user_details', :as => 'save_user_details'

    post     '/rooms/change_image/:image' => 'rooms#change_image', :as => 'change_image'

    resources :users do
        get 'save_user_details', on: :collection
    end

    resources :rooms do
        get 'save_room_details', on: :collection
        post 'change_image', on: :collection
    end

    resources :bookings

    root 'sessions#new'

    # IMPORTANT! This line must be read last and no routes should be below this
    get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    def new
    end
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def index
        if session[:username]=="admin"
            @bookings = Booking.order(:id)
        else
            @bookings = Booking.where(["username = ?", session[:username]])
        end
    end

    def show
        @booking = Booking.find(params[:id])
        @booking.save
        redirect_to(bookings_url)
    end

    def new
        @rooms = Room.all
        @bookings = Booking.where(["status = ?", "Confirmed"])
        @booking = Booking.new
    end
    def edit
        @booking = Booking.find(params[:id])
    end

    def editStatus
        @booking = Booking.find(params[:id])
        @booking.status = params[:status]
        if (@booking.status.downcase=='confirmed' or @booking.status.downcase=='rejected' or @booking.status.downcase=='pending')
            @booking.save
        else
            flash.now.alert = 'Invalid status, unable to be saved'
        end
        redirect_to(bookings_url)
    end

    def create
        @booking = Booking.new(booking_params)
        @bookings = Booking.where(["status = ?", "Confirmed"])
        @rooms = Room.all
        if @booking.roomname.empty?
            flash.now.alert  = 'Please try again and ensure the time slot has been selected.'
            render 'new'
        else
            @booking.username = session[:username]
            @booking.status = "Confirmed"
            @booking.save
            redirect_to(bookings_url)
        end
    end

    def destroy
        @booking = Booking.find(params[:id])
        @booking.destroy

        redirect_to(bookings_url)
    end

    private
    def booking_params
        params.require(:booking).permit(:id, :username, :roomname, :date, :startTime, :endTime, :status)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    protect_from_forgery with: :null_session

    def index
        @rooms = Room.all
    end

    def show
        @room= Room.find(params[:id])
    end

    def new
        @room= Room.new
    end

    def edit
        @room = Room.find(params[:id])
    end

    def create
        @room= Room.new(room_params.except('room_image'))
        @room.save

        photo = params['room']['room_image']

        if photo
            name = photo.original_filename
            extname = name.partition('.').last
            directory = "public/images"
            path = File.join(directory, 'rooms_' + @room.id.to_s + '.'+ extname)

            File.open(path, "wb") do |file|
                file.write(photo.read)
            end
        end
        redirect_to rooms_url
    end

    def destroy
        @room= Room.find(params[:id])
        @room.destroy

        redirect_to(rooms_url)
    end

    def save_room_details
        @room= Room.find(params[:id])
        if @room
            @room.name = params[:name]
            @room.description = params[:desc]

            @room.save
        end
        redirect_to rooms_url
    end

    def change_image
        @room= Room.find(params[:id])
        if @room
            File.delete('public/images/rooms_'+@room.id.to_s+'.jpg') if File.exists?('public/images/rooms_'+@room.id.to_s+'.jpg')
            File.delete('public/images/rooms_'+@room.id.to_s+'.jpeg') if File.exists?('public/images/rooms_'+@room.id.to_s+'.jpeg')
            File.delete('public/images/rooms_'+@room.id.to_s+'.png') if File.exists?('public/images/rooms_'+@room.id.to_s+'.png')

            photo = params[:room_image]

            if photo
                name = photo.original_filename
                extname = name.partition('.').last
                directory = "public/images"
                path = File.join(directory, 'rooms_' + @room.id.to_s + '.'+ extname)

                File.open(path, "wb") do |file|
                    file.write(photo.read)
                end
            end
        end
        redirect_to rooms_url
    end

    private
    def room_params
        params.require(:room).permit(:id, :name, :description, :room_image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        if session[:user_id]
            redirect_to bookings_url
        end
    end

    def create
        user = User.find_by(username: params[:session][:username].downcase)
        if user && user.password==params[:session][:password]
            log_in user
            redirect_to bookings_url
        else
            if params[:session][:username].empty? or params[:session][:password].empty?
                flash.now.alert  = 'Username/password cannot be empty'
            else
                flash.now.alert  = 'Invalid email/password combination'
            end
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user= User.find(params[:id])
    end

    def new
        @user= User.new
    end
    def edit
        @user= User.find(params[:id])
    end

    def create
        @user= User.new(booking_params)
        if @user.username.empty?
            @user.errors.add(:base, "Username field cannot be empty")
        end

        if @user.password.empty?
            @user.errors.add(:base, "Password field cannot be empty")
        end

        if User.exists?(username: @user.username.strip())
            @user.errors.add(:base, "Duplicate username, please enter a new username.")
        end

        if @user.errors.empty?
            @user.save
            redirect_to(users_url)
        else
            render 'new'
        end
    end

    def destroy
        @user= User.find(params[:id])
        @user.destroy

        redirect_to(users_url)
    end

    def save_user_details
        @user= User.find(params[:id])
        if @user && !User.exists?(username: params[:username].strip())
            @user.username = params[:username]
            @user.password = params[:password]

            @user.save
        end
        redirect_to users_url
    end

    private
    def booking_params
        params.require(:user).permit(:id, :username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
        session[:username] = user.username
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        session.delete(:username)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookings/index.html.erb
<%
    if !session[:username]
        controller.redirect_to root_url
    end
%>
<% if flash.each.any? %>
    <div class="btn btn-danger w-100 my-2">
        <% flash.each do |message_type, message| %>
            <div class=" alert-<%= message_type %>"><%= message %></div>
        <% end %>
    </div>
<% end %>

<div class="d-flex justify-content-between py-3">
    <div>
        <h3 class="text-uppercase font-weight-bolder">All Bookings</h3>
    </div>
    <div>
        <%= link_to new_booking_url, {:class => "navicon-content"} do %>
            <div class="btn btn-secondary">
                <i class="fa fa-plus mr-1"></i>New
            </div>
        <% end %>
    </div>
</div>
<div>
    <table class="table table-striped">
        <thead>
        <tr class="text-center text-bold text-upper bg-success text-white"><th colspan="10">Upcoming</th></tr>
        <tr class="text-center">
            <% if session[:username]=="admin" %>
                <th scope="col">Booking ID</th>
                <th scope="col">User</th>
            <% end %>
            <th scope="col">Room</th>
            <th scope="col">Date</th>
            <th scope="col">Start Time</th>
            <th scope="col">End Time</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <% if !@bookings or @bookings.where(["date >= ?", Date.current]).empty? %>
            <tr>
                <td colspan="8" class="text-center">
                    No Current Bookings.
                </td>
            </tr>
        <% else %>
            <% @bookings.where(["date >= ?", Date.current]).each do |booking| %>
                <tr class="text-center">
                    <% if session[:username]=="admin" %>
                        <td class="align-middle text-center"><%= booking.id %></td>
                        <td class="align-middle text-center"><%= booking.username %></td>
                    <% end %>
                    <td class="align-middle text-center"><%= booking.roomname %></td>
                    <td class="align-middle text-center"><%= booking.date.to_date %></td>
                    <td class="align-middle text-center"><%= if booking.startTime.length==4 then booking.startTime else '0'+booking.startTime end %></td>
                    <td class="align-middle text-center"><%= if booking.endTime.length==4 then booking.endTime else '0'+booking.endTime end %></td>
                    <% if session[:username]=="admin" %>
                        <td class="align-middle text-center text-capitalized">
                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-capitalize" style="width: 8em;" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <% if booking.status.downcase == 'confirmed' or booking.status.downcase == 'rejected' or booking.status.downcase == 'pending' %>
                                    <%= booking.status %>
                                <% end %>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <% if booking.status.downcase != 'confirmed' %>
                                    <a class="dropdown-item text-capitalize" href="bookings/editstatus/<%= booking.id %>/Confirmed">Confirmed</a>
                                <% end %>
                                <% if booking.status.downcase != 'pending' %>
                                    <a class="dropdown-item text-capitalize" href="bookings/editstatus/<%= booking.id %>/Pending">Pending</a>
                                <% end %>
                                <% if booking.status.downcase != 'rejected' %>
                                    <a class="dropdown-item text-capitalize" href="bookings/editstatus/<%= booking.id %>/Rejected">Rejected</a>
                                <% end %>
                            </div>
                        </div>
                    </td>
                    <% else %>
                        <td class="align-middle text-center"><%= booking.status %></td>
                    <% end %>
                    <td class="align-middle text-center">
                        <%= link_to 'Delete', booking_path(booking),
                            method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: 'btn btn-danger',
                            style: 'width: 4.5em'
                        %>
                    </td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
    </table>

    <table class="table table-striped mt-4">
        <thead>
        <tr class="text-center text-bold text-upper bg-danger text-white"><th colspan="10">Past Bookings</th></tr>
        <tr class="text-center">
            <% if session[:username]=="admin" %>
                <th scope="col">Booking ID</th>
                <th scope="col">User</th>
            <% end %>
            <th scope="col">Room</th>
            <th scope="col">Date</th>
            <th scope="col">Start Time</th>
            <th scope="col">End Time</th>
            <th scope="col">Status</th>
            <% if session[:username]=="admin" %>
                <th scope="col"></th>
            <% end %>
        </tr>
        </thead>
        <tbody>
        <% if !@bookings or @bookings.where(["date < ?", Date.current]).empty? %>
            <tr>
                <td colspan="8" class="text-center">
                    No Past Bookings.
                </td>
            </tr>
        <% else %>
            <% @bookings.where(["date < ?", Date.current]).each do |booking| %>
                <tr class="text-center">
                    <% if session[:username]=="admin" %>
                        <td class="align-middle text-center"><%= booking.id %></td>
                        <td class="align-middle text-center"><%= booking.username %></td>
                    <% end %>
                    <td class="align-middle text-center"><%= booking.roomname %></td>
                    <td class="align-middle text-center"><%= booking.date.to_date %></td>
                    <td class="align-middle text-center"><%= if booking.startTime.length==4 then booking.startTime else '0'+booking.startTime end %></td>
                    <td class="align-middle text-center"><%= if booking.endTime.length==4 then booking.endTime else '0'+booking.endTime end %></td>
                    <% if session[:username]=="admin" %>
                        <td class="align-middle text-center">
                            <div class="dropdown">
                                <button class="btn dropdown-toggle text-capitalize" style="width: 8em;" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <% if booking.status.downcase == 'confirmed' or booking.status.downcase == 'rejected' or booking.status.downcase == 'pending' %>
                                        <%= booking.status %>
                                    <% end %>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <% if booking.status.downcase != 'confirmed' %>
                                        <a class="dropdown-item text-capitalize" href="bookings/editstatus/<%= booking.id %>/Confirmed">Confirmed</a>
                                    <% end %>
                                    <% if booking.status.downcase != 'pending' %>
                                        <a class="dropdown-item text-capitalize" href="bookings/editstatus/<%= booking.id %>/Pending">Pending</a>
                                    <% end %>
                                    <% if booking.status.downcase != 'rejected' %>
                                        <a class="dropdown-item text-capitalize" href="bookings/editstatus/<%= booking.id %>/Rejected">Rejected</a>
                                    <% end %>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle text-center">
                            <%= link_to 'Delete', booking_path(booking),
                                        method: :delete,
                                        data: { confirm: 'Booking is a past record. Are you sure you want to delete?' },
                                        class: 'btn btn-danger',
                                        style: 'width: 4.5em'
                            %>
                        </td>
                    <% else %>
                        <td class="align-middle text-center">
                            <%= booking.status %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        <% end %>
        </tbody>
    </table>
</div>

app/views/bookings/new.html.erb
<div class="py-3">
    <h3 class="text-uppercase font-weight-bolder">New Booking</h3>
</div>
<% if flash.each.any? %>
    <div class="btn btn-danger w-100 my-2">
        <% flash.each do |message_type, message| %>
            <div class=" alert-<%= message_type %>"><%= message %></div>
        <% end %>
    </div>
<% end %>

<div class="mb-5 pb-5">
    <span id="bookings-all" type="hidden" data-bookings= "<%= @bookings.to_json %>"></span>
    <span id="rooms-all" type="hidden" data-rooms="<%= @rooms.to_json %>"></span>
    <%= form_with scope: :booking, url: bookings_path, local: true do |form| %>

        <div id="new-booking-1" class="p-5">
            <div class="mb-5 text-center">
                <a class="pr-2 text-uppercase font-weight-bold">Select Date:</a>
                <%= form.date_field :date, id:'new-booking-date', :required=>true, :value => Time.now.strftime('%Y-%m-%d') %>
            </div>
            <div>
                <button type="button" id="first-next" class="btn btn-primary float-right">Next</>
            </div>
        </div>

        <div id="new-booking-2" class="p-5"  style="display: none;">
            <%= form.text_field :username, type:'hidden', :value => session[:username] %>
            <%= form.text_field :roomname, type:'hidden' %>
            <%= form.text_field :startTime, type:'hidden' %>
            <%= form.text_field :endTime, type:'hidden' %>

            <div class="d-flex align-items-center float-right px-3">
                <div style="width: 10px; height: 10px; background-color: #28a745"></div>
                <a class="text-uppercase small ml-1 mr-3">Selected</a>
                <div style="width: 10px; height: 10px; background-color: red"></div>
                <a class="text-uppercase small ml-1">Unavailable</a>
            </div>

            <table id="room-table-header" class="table table-dark"><thead><tr><td colspan="12" id="date-placeholder" class="text-center"></td></tr><tr>
                <td class="border-white" style="width: 10%"></td>
                <%
                    time = 800
                   for i in 0..10
                %>
                    <td class="border-white text-center" style="width: 6%"><%= time>=1000 ? time : '0'+time.to_s %></td>
                <%
                    time+=100
                    end
                %>
            </tr></thead></table>

            <table id="room-table-body" class="table">
                <tbody>
                <% for room in @rooms %>
                    <tr id="room_<%= room.id %>">
                        <td class="room-row bg-dark text-white" style="width: 10%"><%= room.name %></td>
                        <div id="room-desc-popup-<%= room.id %>" class="room-desc-popup">
                            <div class="px-3 mb-1 text-uppsercase font-weight-bold"><%= room.name %></div>
                            <img src="/images/rooms_<%= room.id %>.jpg" width="280px">
                            <div class="px-3 mt-1 small"><%= room.description %></div>
                        </div>
                        <%
                            time = 800
                            for i in 0..10
                        %>
                            <td id="room_<%= room.id %>_<%= time %>" class="border-top-0 text-center unselected-cell" style="width: 6%"></td>
                        <%
                            time+=100
                            end
                        %>
                    </tr>
                <% end %>
                </tbody>
            </table>

            <div class="d-flex align-items-center float-right">
                <a class="small font-weight-bold">*Hover over room name to view more details</a>
            </div>

            <div class="mt-5">
                <button type="button" id="second-prev" class="btn btn-primary float-left">Back</>
            </div>

            <div>
                <button type="submit" class="btn btn-primary float-right">Submit</button>
            </div>
        </div>
    <% end %>
</div>

app/views/rooms/index.html.erb
<%
    if !session[:username]
        controller.redirect_to root_url
    elsif session[:username]!="admin"
        controller.redirect_to bookings_url
    end
%>

<div class="d-flex justify-content-between pt-3">
    <div>
        <h3 class="text-uppercase font-weight-bolder">All Rooms</h3>
    </div>
    <div>
        <%= link_to new_room_url, {:class => "navicon-content"} do %>
            <div class="btn btn-secondary">
                <i class="fa fa-plus mr-1"></i>New
            </div>
        <% end %>
    </div>
</div>
<hr>
<div>
    <table id="rooms-data" class="table table-striped mb-5">
        <thead>
        <tr>
            <th scope="col" class="align-middle text-center" style="width: 10%">ID</th>
            <th scope="col" class="align-middle text-center" style="width: 10%">Name</th>
            <th scope="col" class="align-middle text-center" style="width: 70%" colspan="2" class="text-center">Description</th>
            <th scope="col" class="align-middle text-center" style="width: 5%"></th>
        </tr>
        </thead>
        <% @rooms.each do |room| %>
            <tr>
                <td scope="row" class="align-middle text-center"><%= room.id %></td>
                <td class="align-middle text-center"><%= room.name %>

                <% if File.file?"#{Rails.public_path}/images/rooms_"+room.id.to_s+".jpg" or File.file?"#{Rails.public_path}/images/rooms_"+room.id.to_s+".jpeg" or File.file?"#{Rails.public_path}/images/rooms_"+room.id.to_s+".png" %>
                    <td class="align-middle text-center" style="width:25%">
                        <% if File.file?"#{Rails.public_path}/images/rooms_"+room.id.to_s+".jpg" %>
                            <%= image_tag ("/images/rooms_"+room.id.to_s+".jpg"), style:"width: 280px", class: "img-responsive" %>
                        <% elsif File.file?"#{Rails.public_path}/images/rooms_"+room.id.to_s+".png" %>
                            <%= image_tag ("/images/rooms_"+room.id.to_s+".png"), style:"width: 280px", class: "img-responsive" %>
                        <% elsif File.file?"#{Rails.public_path}/images/rooms_"+room.id.to_s+".jpeg" %>
                            <%= image_tag ("/images/rooms_"+room.id.to_s+".jpeg"), style:"width: 280px", class: "img-responsive" %>
                        <% end %>
                        <div class="change-image mt-1" data-id="<%= room.id %>">
                            <i class="fa fa-upload"></i><a class="small text-center"> Change Image</a>
                        </div>
                    </td>
                <% else %>
                    <td class="align-middle text-center">
                        <div class="change-image mt-1" data-id="<%= room.id %>">
                            <i class="fa fa-upload"></i><a class="small text-center"> Add an Image</a>
                        </div>
                    </td>
                <% end %>

                <td class="align-middle" style="width:35%"><%= room.description %></td>
                <td class="align-middle">
                    <button id="edit-room" class="btn btn-primary mb-1 edit-rooms" data-id="<%= room.id %>" data-name="<%= room.name %>" data-description="<%= room.description %>" style="width: 4.5em;">Edit</button>
                    <%= link_to 'Delete', room_path(room),
                                method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: 'btn btn-danger',
                                style: 'width: 4.5em'
                    %>
                </td>
            </tr>
        <% end %>
    </table>
</div>

<div class="grey-screen"></div>
<div id="edit-room-popup" class="edit-popup">
    <div id="edit-rooms-close" class="float-right close-button"><i class="fa fa-times"></i></div>
    <div class="p-4">
        <form action="/rooms/save_room_details" method="get">
            <input type="hidden" id="edit-room-id" name="id"><br>
            Room Name:  <input type="text" id="edit-room-name" name="name" class="mb-2"><br>
            Description:<textarea id='edit-room-desc' name="desc" style='width: 90%; height: 8em; resize: none; float: bottom'></textarea>
            <button id="edit-room-save" type="submit" class="btn btn-primary mt-4 float-right">Save</button>
        </form>
    </div>
</div>

<div id="change-image-popup" class="change-image-popup">
    <div id="change-image-close" class="float-right close-button"><i class="fa fa-times"></i></div>
    <div class="p-4 mx-5">
        <form action="/rooms/change_image" enctype="multipart/form-data" accept-charset="UTF-8" method="post">
            <input type="hidden" id="change-image-id" name="id"><br>
            <input type="file" id="change-image-file" name="room_image">
            <button type="submit" class="btn btn-primary mt-4 float-right mr-5 pt-1">Save</button>
        </form>
    </div>
</div>

app/views/rooms/new.html.erb
<div class="py-3">
    <h3 class="text-uppercase font-weight-bolder">Add New Room</h3>
</div>
<% if flash.each.any? %>
    <div class="btn btn-danger w-100 my-2">
        <% flash.each do |message_type, message| %>
            <div class=" alert-<%= message_type %>"><%= message %></div>
        <% end %>
    </div>
<% end %>
<div class="d-flex d-lg-block justify-content-center">
    <%= form_with scope: :room, url: rooms_path, local: true do |f| %>
        <div class="d-flex my-3">
            <div>
                <a class="pr-2">Upload an Image:</a>
                <%= f.file_field :room_image %>
            </div>
        </div>
        <div class="d-flex my-3">
            <div>
                <a class="pr-2">Room Name:</a>
                <%= f.text_field :name, style: 'width: 396px' %>
            </div>
        </div>
        <div class="d-flex my-3">
            <div>
                <a class="pr-2">Description:</a>
                <br>
                <%= f.text_area :description, style:'width: 500px; height: 8em; resize: none; float: bottom' %>
            </div>
        </div>
        <div>
            <%= f.submit 'Add New Room', :class=>'btn btn-primary' %>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<%
    if session[:username]!="admin"
        controller.redirect_to welcome_index_url
    end
%>
<% if flash.each.any? %>
    <div class="btn btn-danger w-100 my-2">
        <% flash.each do |message_type, message| %>
            <div class=" alert-<%= message_type %>"><%= message %></div>
        <% end %>
    </div>
<% end %>

<div class="d-flex justify-content-between py-3">
    <div>
        <h3 class="text-uppercase font-weight-bolder">All Users</h3>
    </div>
    <div>
        <%= link_to new_user_url, {:class => "navicon-content"} do %>
            <div class="btn btn-secondary">
                <i class="fa fa-plus mr-1"></i>New
            </div>
        <% end %>
    </div>
</div>
<table id="users-data" class="table table-striped mb-4">
    <thead>
    <tr class="text-center">
        <th scope="col">User ID</th>
        <th scope="col">User Name</th>
        <th scope="col">Password</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr class="text-center">
            <td><%= user.id %></td>
            <td><%= user.username %></td>
            <td><%= user.password %></td>
            <td>
                <button id="edit-user" class="btn btn-primary edit-users" data-id="<%= user.id %>" data-username="<%= user.username %>" data-password="<%= user.password %>" style="width: 4.5em;">Edit</button>
                <% if user.username != "admin" %>
                    <%= link_to 'Delete', user_path(user),
                                method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: 'btn btn-danger',
                                style: 'width: 4.5em'
                    %>
                <% end %>
            </td>

        </tr>
    <% end %>
    </tbody>
</table>

<div class="grey-screen"></div>
<div id="edit-user-popup" class="edit-popup">
    <div id="edit-users-close" class="float-right close-button"><i class="fa fa-times"></i></div>
    <div class="p-4">
        <form action="/users/save_user_details" method="get">
            <input type="hidden" id="edit-user-id" name="id"><br>
            Username:<input type="text" id="edit-user-name" name="username" class="ml-2 mb-2"><br>
            Password:<input type="text" id='edit-user-pw' name="password" class="ml-2">
            <button id="edit-user-save" type="submit" class="btn btn-primary mt-4 float-right">Save</button>
        </form>
    </div>
</div>

app/views/users/new.html.erb
<%
    if session[:username]!="admin"
        controller.redirect_to welcome_index_url
    end
%>
<div class="py-3">
    <h3 class="text-uppercase font-weight-bolder">New User</h3>
</div>
<div>
    <% if @user.errors.any? %>
        <div>
            <% @user.errors.full_messages.each do |msg| %>
                <div class="btn btn-danger error-message-container mb-1"><%= msg %></div>
            <% end %>
        </div>
    <% end %>
    <%= form_with scope: :user, url: users_path, local: true do |form| %>
        <div class="d-flex my-3">
            <div class="mx-2">
                <a class="pr-2">User Name</a>
                <%= form.text_field :username %>
            </div>
            <div>
                <a class="pr-2">Password</a>
                <%= form.text_field :password %>
            </div>
        </div>

        <div>
            <%= form.submit 'Add New User', :class=>'btn btn-primary' %>
        </div>
    <% end %>
</div>

app/views/welcome/index.html.erb
<%
    if !session[:user_id]
        controller.redirect_to root_url
    end
    if session[:username] != "admin"
        controller.redirect_to bookings_url
    end
%>
<div class="pt-3 pb-1">
    <h3 class="text-uppercase font-weight-bolder">Recent Activities</h3>
</div>
<hr>